= SoMLabs BSP

Yocto Project based BSP for SoMLabs boards:
http://wiki.somlabs.com/index.php?title=VisionSOM-6ULL

SoMLabs BSP is based on FSL Community BSP. See also:
https://github.com/Freescale/fsl-community-bsp-platform
http://freescale.github.io/
=======

This manual describes how to deploy the image build environment under Ubuntu 16.04.5.

Install necessary packages:
[source,console]
$: sudo apt install build-essential git-core libncurses5-dev flex bison texinfo zip unzip zlib1g-dev gettext u-boot-tools g++ xz-utils mtd-utils gawk diffstat gcc-multilib lzop bc chrpath

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: apt install repo

Download the BSP source:

[source,console]
$: mkdir somlabs
$: cd somlabs
$: repo init -u https://github.com/sgunin/somlabs-bsp.git -b warrior
$: repo sync

Thud repos is Yocto 2.6.1. https://www.yoctoproject.org/docs/?section=developer-manuals

At the end of the commands you have every metadata you need to start work with.

Setup build environment:

[source,console]
$: . setup-environment build

Build standart SomLabs console image
[source,console]
$: bitbake console-image

You can also build extended images (from meta-somlabs-extra):
[source,console]
$: bitbake console-extraimage
$: bitbake console-extraimage-debug

After the build is finished, you can browse the catalog with the build results
[source,console]
$: ls -la ../tmp/deploy/images/visionsom6ull/

The directory contains the following files:

console-image-visionsom6ull.wic.gz - symbol link to GZipped SD card image

somlabs-visionsom-6ul*.dtb - symbol links device tree binary compiled files

u-boot*.imx* - symbol links to UBoot binary files

zImage - symbol link to kernel image

The file name includes the build date and time. 
For example, the full name of the file to write to the SD card will be console-image-visionsom6ull-20181220081500.rootfs.wic.gz.

To write to the SD card, you need to run the following command
[source,console]
$: cd ../tmp/deploy/images/visionsom6ull/
$: zcat console-image-visionsom6ull-20181220081500.rootfs.wic.gz | sudo dd of=/dev/sdb bs=1M iflag=fullblock oflag=direct conv=fsync

where /dev/sdb is the name of the SDCard device in the system (can be obtained using the command lsblk).
