= SoMLabs BSP

Yocto Project based BSP for SoMLabs boards:
http://wiki.somlabs.com/index.php?title=VisionSOM-6ULL

SoMLabs BSP is based on FSL Community BSP. See also:
https://github.com/Freescale/fsl-community-bsp-platform
http://freescale.github.io/

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: apt update
$: apt install -y repo

Download the BSP source:

[source,console]
$: mkdir somlabs
$: cd somlabs
$: repo init -u https://github.com/sgunin/somlabs-bsp.git -b rocko
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To start a simple image build:

[source,console]
$: . setup-environment build

Buid console image
[source,console]
$: bitbake console-image

or build QT5 image
[source,console]
$: bitbake qt5-image

After build finished, list result images catalog
[source,console]
$: ls -la tmp/deploy/images/visionsom6ull/

and write SD card image to SD card
[source,console]
$: sudo dd of=/dev/sdc if=tmp/deploy/images/myd-y6ul14x14/core-image-base-myd-y6ul14x14.wic bs=1M iflag=fullblock oflag=direct conv=fsync
