= SoMLabs BSP

Yocto Project based BSP for SoMLabs boards:
http://wiki.somlabs.com/index.php?title=VisionSOM-6ULL

SoMLabs BSP is based on FSL Community BSP. See also:
https://github.com/Freescale/fsl-community-bsp-platform
http://freescale.github.io/

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: apt update
$: apt install -y repo

Download the BSP source:

[source,console]
$: mkdir somlabs
$: cd somlabs
$: repo init -u https://github.com/sgunin/somlabs-bsp.git -b rocko
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To start a simple image build:

[source,console]
$: . setup-environment build

Build console image
[source,console]
$: bitbake console-image

or build QT5 image
[source,console]
$: bitbake qt5-image

After the build is finished, you can browse the catalog with the build results
[source,console]
$: ls -la tmp/deploy/images/visionsom6ull/

The directory contains the following files:

console-image-visionsom6ull.wic.gz - symbol link to GZipped SD card image

somlabs-visionsom-6ul*.dtb - symbol links device tree binary compiled files

u-boot*.imx* - symbol links to UBoot binary files

zImage - symbol link to kernel image

The file name includes the build date and time. 
For example, the full name of the file to write to the SD card will be console-image-visionsom6ull-20181220081500.rootfs.wic.gz.

To write to the SD card, you need to run the following command
[source,console]
$: cd tmp/deploy/images/visionsom6ull/
$: zcat console-image-visionsom6ull-20181220081500.rootfs.wic.gz | sudo dd of=/dev/sdb bs=1M iflag=fullblock oflag=direct conv=fsync

where /dev/sdb is the name of the SDCard device in the system (can be obtained using the command lsblk).
